# Generated by Django 5.1.1 on 2024-09-13 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='categoria',
            field=models.TextField(blank=True, null=True),
        ),
    ]
